/**
 * ASTRALMIA — Supplier Database
 * 12 suppliers across 6 categories
 */

const SUPPLIERS = [
  // ── CRISTAIS ─────────────────────────────────────────────────────
  {
    id: "aliexpress-crystals",
    name: "AliExpress — Crystal Store",
    platform: "aliexpress.com",
    url: "https://aliexpress.com/wholesale?SearchText=healing+crystal",
    category: "cristais",
    products: [
      { name: "Quartzo Rosa Polido 3cm", unitCost: 3.50, moq: 1, inStock: true },
      { name: "Ametista Bruta 5cm", unitCost: 4.20, moq: 1, inStock: true },
      { name: "Obsidiana Negra Esfera 4cm", unitCost: 5.80, moq: 1, inStock: true },
      { name: "Selenite Vara 20cm", unitCost: 2.90, moq: 1, inStock: true },
    ],
    shippingCost: 2.50,
    freeShippingAbove: 25,
    deliveryDays: { min: 12, max: 25 },
    currency: "EUR",
    rating: 4.6,
  },
  {
    id: "dhgate-crystals",
    name: "DHgate — Crystal Wholesale",
    platform: "dhgate.com",
    url: "https://dhgate.com/wholesale/crystals.html",
    category: "cristais",
    products: [
      { name: "Quartzo Transparente Ponto", unitCost: 2.80, moq: 10, inStock: true },
      { name: "Labradorite Polida", unitCost: 6.50, moq: 5, inStock: true },
      { name: "Pirita Cubo Natural", unitCost: 4.10, moq: 5, inStock: true },
    ],
    shippingCost: 3.20,
    freeShippingAbove: 40,
    deliveryDays: { min: 14, max: 28 },
    currency: "EUR",
    rating: 4.4,
  },
  {
    id: "wholesale-crystals-uk",
    name: "Wholesale Crystal Supplier UK",
    platform: "wholesalecrystalsupplier.com",
    url: "https://wholesalecrystalsupplier.com",
    category: "cristais",
    products: [
      { name: "Ametista Geode Pequena", unitCost: 8.50, moq: 3, inStock: true },
      { name: "Cristal de Quartzo Bruto 100g", unitCost: 5.20, moq: 5, inStock: false },
      { name: "Torre de Selenite 10cm", unitCost: 4.80, moq: 5, inStock: true },
    ],
    shippingCost: 6.50,
    freeShippingAbove: 80,
    deliveryDays: { min: 5, max: 10 },
    currency: "EUR",
    rating: 4.8,
    promo: "10% desconto em encomendas acima de €100",
  },
  // ── TAROT ─────────────────────────────────────────────────────────
  {
    id: "aliexpress-tarot",
    name: "AliExpress — Tarot Decks",
    platform: "aliexpress.com",
    url: "https://aliexpress.com/wholesale?SearchText=tarot+deck",
    category: "tarot",
    products: [
      { name: "Rider Waite Tarot (78 cartas)", unitCost: 7.20, moq: 1, inStock: true },
      { name: "Tarot Marselha Clássico", unitCost: 6.80, moq: 1, inStock: true },
      { name: "Oracle Cards 44 cartas", unitCost: 9.50, moq: 1, inStock: true },
    ],
    shippingCost: 2.50,
    freeShippingAbove: 25,
    deliveryDays: { min: 12, max: 22 },
    currency: "EUR",
    rating: 4.5,
    promo: "Frete grátis acima de €25",
  },
  {
    id: "dhgate-tarot",
    name: "DHgate — Tarot Wholesale",
    platform: "dhgate.com",
    url: "https://dhgate.com/wholesale/tarot+cards.html",
    category: "tarot",
    products: [
      { name: "Thoth Tarot Deck", unitCost: 10.20, moq: 5, inStock: true },
      { name: "Tarot Egipcio Gold Edition", unitCost: 13.50, moq: 3, inStock: false },
    ],
    shippingCost: 3.20,
    freeShippingAbove: 50,
    deliveryDays: { min: 14, max: 25 },
    currency: "EUR",
    rating: 4.3,
  },
  // ── INCENSO ──────────────────────────────────────────────────────
  {
    id: "mystic-moments-incense",
    name: "Mystic Moments UK",
    platform: "mysticmoments.co.uk",
    url: "https://www.mysticmoments.co.uk",
    category: "incenso",
    products: [
      { name: "Incenso Nag Champa 100g", unitCost: 1.80, moq: 10, inStock: true },
      { name: "Incenso Sândalo Premium 50g", unitCost: 2.20, moq: 10, inStock: true },
      { name: "Palo Santo Varinhas 10un", unitCost: 3.50, moq: 5, inStock: true },
    ],
    shippingCost: 5.00,
    freeShippingAbove: 60,
    deliveryDays: { min: 4, max: 8 },
    currency: "EUR",
    rating: 4.9,
  },
  {
    id: "ankorstore-incense",
    name: "Ankorstore EU — Incenso",
    platform: "ankorstore.com",
    url: "https://ankorstore.com/search?query=incense",
    category: "incenso",
    products: [
      { name: "Incenso Meditation Blend 120g", unitCost: 2.50, moq: 6, inStock: true },
      { name: "Cones de Incenso Lavanda 30un", unitCost: 1.60, moq: 12, inStock: true },
    ],
    shippingCost: 4.50,
    freeShippingAbove: 100,
    deliveryDays: { min: 3, max: 6 },
    currency: "EUR",
    rating: 4.7,
    promo: "Primeira encomenda sem frete mínimo",
  },
  // ── VELAS ────────────────────────────────────────────────────────
  {
    id: "ankorstore-candles",
    name: "Ankorstore EU — Velas",
    platform: "ankorstore.com",
    url: "https://ankorstore.com/search?query=candles+ritual",
    category: "velas",
    products: [
      { name: "Vela Ritual Branca 15cm", unitCost: 1.20, moq: 12, inStock: true },
      { name: "Vela de Soja Aromatizada 150g", unitCost: 3.80, moq: 6, inStock: true },
      { name: "Vela Colorida Pack 7 Chakras", unitCost: 5.50, moq: 4, inStock: true },
    ],
    shippingCost: 4.50,
    freeShippingAbove: 100,
    deliveryDays: { min: 3, max: 6 },
    currency: "EUR",
    rating: 4.7,
  },
  {
    id: "faire-candles",
    name: "Faire EU — Velas Artesanais",
    platform: "faire.com",
    url: "https://faire.com/search?q=ritual+candles",
    category: "velas",
    products: [
      { name: "Vela Cera de Abelha Ritual 200g", unitCost: 6.20, moq: 4, inStock: true },
      { name: "Vela Lua Cheia Lavanda", unitCost: 7.50, moq: 3, inStock: true },
    ],
    shippingCost: 6.00,
    freeShippingAbove: 120,
    deliveryDays: { min: 5, max: 10 },
    currency: "EUR",
    rating: 4.8,
  },
  // ── LIVROS ───────────────────────────────────────────────────────
  {
    id: "aliexpress-books",
    name: "AliExpress — Livros Esotéricos",
    platform: "aliexpress.com",
    url: "https://aliexpress.com/wholesale?SearchText=astrology+book",
    category: "livros",
    products: [
      { name: "Livro Astrologia para Iniciantes", unitCost: 4.50, moq: 1, inStock: true },
      { name: "Guia Completo de Tarot", unitCost: 6.80, moq: 1, inStock: true },
    ],
    shippingCost: 2.50,
    freeShippingAbove: 30,
    deliveryDays: { min: 15, max: 30 },
    currency: "EUR",
    rating: 4.2,
  },
  // ── JOIAS ────────────────────────────────────────────────────────
  {
    id: "aliexpress-jewelry",
    name: "AliExpress — Joias Esotéricas",
    platform: "aliexpress.com",
    url: "https://aliexpress.com/wholesale?SearchText=crystal+jewelry+esoteric",
    category: "joias",
    products: [
      { name: "Pendente Ametista Prata 925", unitCost: 5.50, moq: 1, inStock: true },
      { name: "Pulseira Quartzo Rosa", unitCost: 3.20, moq: 1, inStock: true },
      { name: "Brincos Lua Prata", unitCost: 4.80, moq: 1, inStock: true },
    ],
    shippingCost: 2.50,
    freeShippingAbove: 25,
    deliveryDays: { min: 12, max: 22 },
    currency: "EUR",
    rating: 4.5,
    promo: "Compra 2 leva 3 em pulseiras",
  },
  {
    id: "dhgate-jewelry",
    name: "DHgate — Joias Grosso",
    platform: "dhgate.com",
    url: "https://dhgate.com/wholesale/crystal+jewelry.html",
    category: "joias",
    products: [
      { name: "Colar Olho de Tigre Dourado", unitCost: 6.80, moq: 5, inStock: true },
      { name: "Anel Ajustável Cristal", unitCost: 2.90, moq: 10, inStock: true },
    ],
    shippingCost: 3.20,
    freeShippingAbove: 50,
    deliveryDays: { min: 14, max: 28 },
    currency: "EUR",
    rating: 4.4,
  },
];

module.exports = { SUPPLIERS };
