module.exports = {
  apps: [
    {
      name: "astralmia-engine",
      script: "engine/main.js",
      cwd: __dirname,
      node_args: "--experimental-vm-modules",
      instances: 1,
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
      watch: false,
      max_memory_restart: "512M",
      env: {
        NODE_ENV: "production",
        ASTRALMIA_PORT: "4002",
        SCAN_INTERVAL_HOURS: "4",
      },
      error_file: "/var/log/astralmia/engine-error.log",
      out_file: "/var/log/astralmia/engine-out.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "openclaw-gateway",
      script: "openclaw",
      args: "gateway --port 18789",
      cwd: "/home/ubuntu",
      instances: 1,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 10000,
      watch: false,
      max_memory_restart: "1G",
      env: {
        NODE_ENV: "production",
      },
      error_file: "/var/log/astralmia/openclaw-error.log",
      out_file: "/var/log/astralmia/openclaw-out.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "caela-engine",
      script: "../bot/server.js",
      cwd: __dirname,
      instances: 1,
      autorestart: true,
      max_restarts: 30,
      restart_delay: 5000,
      watch: false,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
        BOT_PORT: "4001",
      },
      error_file: "/var/log/astralmia/caela-error.log",
      out_file: "/var/log/astralmia/caela-out.log",
      merge_logs: true,
      time: true,
    },
  ],
};
